=== Tiburubi/Pagina-coches/Tarea 1 HTML Y CSS (Rubén Mateos)/inventario.dtd
<!-- DTD para el inventario de coches de la empresa -->
<!ELEMENT inventario (coche+)>
<!ELEMENT coche (marca, usuario, modelo)>
<!ELEMENT marca (#PCDATA)>
<!ELEMENT usuario (#PCDATA)>
<!ELEMENT modelo (#PCDATA)>
<!ATTLIST coche
    id ID #REQUIRED
>

=== Tiburubi/Pagina-coches/Tarea 1 HTML Y CSS (Rubén Mateos)/inventario.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE inventario SYSTEM "inventario.dtd">
<inventario>
    <coche id="CO001">
        <marca>Lamborghini</marca>
        <usuario>Ruben Mateos Diaz Ropero</usuario>
        <modelo>Huracan Performante</modelo>
    </coche>
    <coche id="CO002">
        <marca>Ferrari</marca>
        <usuario>Jose Luis Moreno</usuario>
        <modelo>488 GTB</modelo>
    </coche>
    <coche id="CO003">
        <marca>Ford</marca>
        <usuario>Luis Diaz</usuario>
        <modelo>Mustang Shellby</modelo>
    </coche>
    <coche id="CO004">
        <marca>Chevrolet</marca>
        <usuario>Pedro Guindal</usuario>
        <modelo>Corevtte C8</modelo>
    </coche>
</inventario>
